    #TASK

#Each new term in the fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ....
#By considering the terms in the fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    #SOLUTION

a,b = 0, 1
even_fibo = []

while b < 4000000 :
  a,b = b, a+b
  if b % 2 == 0 :
    even_fibo += [b]
    
print(sum(even_fibo))    
